//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 30.11.2021 15:23:31
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace TenderDbContext
{

    public partial class CitizenDocumentDto
    {

        #region Properties

        public int Id { get; set; }

        public int TypeId { get; set; }

        public int CitizenId { get; set; }

        public string Number { get; set; }

        #endregion
    }

}
