//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30.11.2021 15:23:31
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TenderDbContext
{
    /// <summary>
    /// There are no comments for CitizenConfiguration in the schema.
    /// </summary>
    public partial class CitizenConfiguration : IEntityTypeConfiguration<Citizen>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<Citizen> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<Citizen> builder)
        {
            builder.ToTable(@"Citizens", @"dbo");
            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            builder.Property(x => x.SurName).HasColumnName(@"SurName").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType(@"nvarchar(100)").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.Patronymic).HasColumnName(@"Patronymic").HasColumnType(@"nvarchar(100)").ValueGeneratedNever().HasMaxLength(100);
            builder.Property(x => x.DateOfBirth).HasColumnName(@"DateOfBirth").HasColumnType(@"date").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.DateOfDeath).HasColumnName(@"DateOfDeath").HasColumnType(@"date").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasIndex(@"Id").IsUnique(true);
            builder.HasMany(x => x.CitizenDocuments).WithOne(op => op.Citizen).OnDelete(DeleteBehavior.Cascade).HasForeignKey(@"CitizenId").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<Citizen> builder);

        #endregion
    }

}
