//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30.11.2021 15:23:31
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TenderDbContext
{
    /// <summary>
    /// There are no comments for CitizenDocumentTypeConfiguration in the schema.
    /// </summary>
    public partial class CitizenDocumentTypeConfiguration : IEntityTypeConfiguration<CitizenDocumentType>
    {
        /// <summary>
        /// There are no comments for Configure(EntityTypeBuilder<CitizenDocumentType> builder) method in the schema.
        /// </summary>
        public void Configure(EntityTypeBuilder<CitizenDocumentType> builder)
        {
            builder.ToTable(@"CitizenDocumentTypes", @"dbo");
            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            builder.HasKey(@"Id");
            builder.HasIndex(@"Id").IsUnique(true);
            builder.HasMany(x => x.CitizenDocuments).WithOne(op => op.CitizenDocumentType).HasForeignKey(@"TypeId").IsRequired(true);

            CustomizeConfiguration(builder);
        }

        #region Partial Methods

        partial void CustomizeConfiguration(EntityTypeBuilder<CitizenDocumentType> builder);

        #endregion
    }

}
